# Generated by Django 4.2.4 on 2023-09-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbase',
            name='firstname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
